# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Rafael Fontenelle <rffontenelle@gmail.com>, 2022
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.10\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-01-10 16:06+0000\n"
"PO-Revision-Date: 2022-11-05 17:21+0000\n"
"Last-Translator: Rafael Fontenelle <rffontenelle@gmail.com>, 2022\n"
"Language-Team: Ukrainian (https://app.transifex.com/python-doc/teams/5390/"
"uk/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: uk\n"
"Plural-Forms: nplurals=4; plural=(n % 1 == 0 && n % 10 == 1 && n % 100 != "
"11 ? 0 : n % 1 == 0 && n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % "
"100 > 14) ? 1 : n % 1 == 0 && (n % 10 ==0 || (n % 10 >=5 && n % 10 <=9) || "
"(n % 100 >=11 && n % 100 <=14 )) ? 2: 3);\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "Винятки"

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr "**Вихідний код:** :source:`Lib/asyncio/exceptions.py`"

#: ../../library/asyncio-exceptions.rst:16
msgid "The operation has exceeded the given deadline."
msgstr ""

#: ../../library/asyncio-exceptions.rst:19
msgid ""
"This exception is different from the builtin :exc:`TimeoutError` exception."
msgstr ""

#: ../../library/asyncio-exceptions.rst:25
msgid "The operation has been cancelled."
msgstr "Операцію скасовано."

#: ../../library/asyncio-exceptions.rst:27
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""
"Цей виняток можна перехопити для виконання спеціальних операцій, коли "
"асинхронні завдання скасовуються. Майже в усіх ситуаціях виняток потрібно "
"підняти повторно."

#: ../../library/asyncio-exceptions.rst:33
msgid ":exc:`CancelledError` is now a subclass of :class:`BaseException`."
msgstr ":exc:`CancelledError` тепер є підкласом :class:`BaseException`."

#: ../../library/asyncio-exceptions.rst:38
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr "Недійсний внутрішній стан :class:`Task` або :class:`Future`."

#: ../../library/asyncio-exceptions.rst:40
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""
"Може бути викликано в таких ситуаціях, як встановлення значення результату "
"для об’єкта *Future*, для якого вже встановлено значення результату."

#: ../../library/asyncio-exceptions.rst:46
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""
"Системний виклик \"sendfile\" недоступний для даного сокета або типу файлу."

#: ../../library/asyncio-exceptions.rst:49
msgid "A subclass of :exc:`RuntimeError`."
msgstr "Підклас :exc:`RuntimeError`."

#: ../../library/asyncio-exceptions.rst:54
msgid "The requested read operation did not complete fully."
msgstr "Запитана операція читання не завершена повністю."

#: ../../library/asyncio-exceptions.rst:56
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr "Створено :ref:`asyncio stream API <asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:58
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr "Цей виняток є підкласом :exc:`EOFError`."

#: ../../library/asyncio-exceptions.rst:62
msgid "The total number (:class:`int`) of expected bytes."
msgstr "Загальна кількість (:class:`int`) очікуваних байтів."

#: ../../library/asyncio-exceptions.rst:66
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr "Рядок із :class:`bytes` прочитано до кінця потоку."

#: ../../library/asyncio-exceptions.rst:71
msgid "Reached the buffer size limit while looking for a separator."
msgstr "Досягнуто обмеження розміру буфера під час пошуку роздільника."

#: ../../library/asyncio-exceptions.rst:73
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr "Створено :ref:`asyncio stream API <asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:77
msgid "The total number of to be consumed bytes."
msgstr "Загальна кількість спожитих байтів."
